### ISSUE TITLE
Json parse error

### ISSUE THREAD

**Issue by sh4ka** [junkdog/glim#3]
Hello, I am experiencing a JSON parse error, and I would like to fix/debug it myself, and I kindly ask for some initial tips on how to debug the app. Thank you so much for your support!

![Drawing](https://github.com/user-attachments/assets/b54608f8-b0ef-41fa-8279-0a48c5442b84)

**Comment by sh4ka** [comment]
Found a way to debug the issue, problem lies in Serde so I am closing this. Sorry to bother you!

**Comment by junkdog** [comment]
> Sorry to bother you!

You're not bothering anyone!

Did the issue stem from you manually editing the file or did glim serialize it wrongly? If it's the latter I'd like to fix it in glim.

**Comment by sh4ka** [comment]
Glim serialized it incorrectly, the error is found at src/client.rs:263

**Comment by junkdog** [comment]
Thanks!

**Comment by junkdog** [comment]
supposedly fixed by #5, closing this for the time being

**Comment by sh4ka** [comment]
Hey I just wanted to let you know that this is now working as expected. Thank you so much for your support!
